# Generated by Django 4.1.5 on 2023-01-13 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни нендели',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Вид единоборства',
                'verbose_name_plural': 'Виды единоборств',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.PositiveIntegerField(auto_created=True, default=0, verbose_name='Текущее')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('price', models.PositiveIntegerField(default=2000, verbose_name='Цена')),
                ('hall_number', models.PositiveIntegerField(verbose_name='Номер зала')),
                ('max_numb', models.PositiveIntegerField(verbose_name='Максимум')),
                ('photo', models.ImageField(upload_to='sections', verbose_name='Фото')),
                ('duration', models.PositiveIntegerField(default=90, verbose_name='Длительность')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('days', models.ManyToManyField(to='sport.days', verbose_name='Дни проведения')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sport.view', verbose_name='Вид единоборств')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ['time_create'],
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплата')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sport.section', verbose_name='Секция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Тренирующийся')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['id'],
            },
        ),
    ]
